#!/usr/bin/env php
<?php

use Yaklass\Spider;
use Yaklass\XpathReader;
use Yaklass\StatsStorage;

$file = __DIR__;
if (file_exists($file = __DIR__ . "/../../autoload.php")) {
  /** @noinspection PhpIncludeInspection */
  require $file;
}
else if (file_exists($file = __DIR__ . "/vendor/autoload.php")) {
  /** @noinspection PhpIncludeInspection */
  require $file;
}
else {
  die("Can't find autoload.php");
}

//
// Get data from Yaklass
//
try {
  $spider = new Spider("credentials.json");
  $html = $spider->getTopPage();
}
catch (Exception $e) {
  echo "Unable to fetch data:\n\t" . $e->getMessage();
  exit(1);
}
unset($spider);

//
// Parse data with XPath
//
$xp = new XPathReader($html);
try {
  $stats = [];
  $students = $xp->getList("//div[@class='classmates-top']//div[@class='top-list']/div");
  foreach ($students as $i => $student) {
    $stats[] = [
      'id' => preg_replace('~/profile/~', '', $xp->getAttr("div[@class='name']/a/@href", $student)),
      'name' => $xp->getText("div[@class='name']/a", $student),
      'points' => $xp->getText("div[@class='points']", $student),
    ];
  }
} catch (Exception $e) {
  echo "Error(s): " . $e->getMessage();
  exit(1);
}

//
// Save data to csv
//
try {
  $storage = new StatsStorage();
  $storage->save($stats);
  echo "New data are saved.";
} catch (Exception $e) {
  echo "Error(s): " . $e->getMessage();
  exit(1);
}

